name: buildtritoninferenceserver
on: workflow_dispatch

jobs:

  buildtritoninferenceserver:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install Prerequisites
        run:  sudo add-apt-repository -y ppa:mhier/libboost-latest && sudo apt-get update && sudo apt-get install -y git build-essential cmake rapidjson-dev libssl-dev libre2-dev libb64-dev libarchive-dev libnuma-dev libboost1.81-dev && sudo pip install numpy tritonclient[all] 
        
      - name: Build Backend
        run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DTRITON_ENABLE_GPU=0 -DTRITON_BACKEND_REPO_TAG=r24.05 -DTRITON_CORE_REPO_TAG=r24.05 -DTRITON_COMMON_REPO_TAG=r24.05 -DCMAKE_INSTALL_PREFIX=$PWD/../install && make install && find $PWD/../install
      
      - name: Clone Triton
        run: git clone https://github.com/triton-inference-server/server --branch r24.05 --single-branch --depth 1

      - name: Build Triton
        run: cd server && python ./build.py -v --no-container-build --enable-logging --enable-stats --enable-tracing --build-dir="$PWD/build" --backend python --backend=ensemble --extra-core-cmake-arg=TRITON_ENABLE_GRPC=OFF --extra-core-cmake-arg=TRITON_ENABLE_HTTP=ON  --extra-core-cmake-arg=TRITON_ENABLE_ENSEMBLE=ON
      
      - name: Test Backend
        run: |
            cp install/backends/recommended/libtriton_recommended.so $PWD/recommended_models/1
            find server/build/opt
            server/build/opt/tritonserver/bin/tritonserver --model-repository $PWD/recommended_models &
            sleep 30s
      #      python recommended_client.py
      #
      #- name: Archive artifacts
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: opt
      #    path: server/build/opt/
